[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "shuffler"
version = "0.1.0"
description = ""
authors = ["Tony"]

[tool.poetry.dependencies]
python = "^3.9"
embit = "0.5.0"
pytest = "7.1.2"
